logging:
  level:
    io:
      pivotal: INFO
security:
  basic:
    enabled: false # turn of securing our application endpoints

management:
  security:
    enabled: false # turn of securing the actuator endpoints

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-qa.cfapps.haas-123.pez.pivotal.io/quote
